USE TM;

CREATE OR REPLACE TABLE COLOR_SCHEMES (
        ID INT PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL,
        TEXT_COLOR VARCHAR(7) NOT NULL,
        BACKGROUND_COLOR VARCHAR(7) NOT NULL
);
