USE TM;

DELIMITER $$

CREATE OR REPLACE PROCEDURE DROP_ALL_PROCEDURES()
BEGIN
	DECLARE DONE INT DEFAULT FALSE;
	DECLARE A CHAR(64);
	DECLARE CUR CURSOR FOR SELECT ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE='PROCEDURE' AND ROUTINE_SCHEMA=DATABASE();
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;

	OPEN CUR;

	READ_LOOP: LOOP
		FETCH CUR INTO A;

		IF DONE THEN
			LEAVE READ_LOOP;
		END IF;

		IF A != 'DROP_ALL_PROCEDURES' THEN
			SET @S = CONCAT('DROP PROCEDURE IF EXISTS ', A);
			PREPARE STMT FROM @S;
			EXECUTE STMT;
			DEALLOCATE PREPARE STMT;
		END IF;
	END LOOP;

	CLOSE CUR;
END$$

DELIMITER ;

CALL DROP_ALL_PROCEDURES();

