DROP DATABASE TM;
CREATE OR REPLACE DATABASE TM;

CREATE USER 'TM'@'localhost' IDENTIFIED BY '0000';
GRANT ALL PRIVILEGES ON TM.* TO 'TM'@'localhost';
FLUSH PRIVILEGES;

SOURCE 0_create_drop_all_procedures.sql;
CALL DROP_ALL_PROCEDURES();
