CREATE OR REPLACE TABLE USERS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	USERNAME VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD_HASH CHAR(60) NOT NULL,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	PROFILE_PICTURE BLOB
);
