CREATE OR REPLACE TABLE USERS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	USERNAME VARCHAR(255) NOT NULL UNIQUE,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD_HASH CHAR(60) NOT NULL,
	PROFILE_PICTURE_PATH VARCHAR(255)
);

CREATE OR REPLACE TABLE COLOR_SCHEMES (
	ID INT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	TEXT_COLOR VARCHAR(7) NOT NULL,
	BACKGROUND_COLOR VARCHAR(7) NOT NULL
);

CREATE OR REPLACE TABLE CATEGORIES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	OWNER_ID INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	COLOR_SCHEME_ID INT NOT NULL,

	FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID),
	FOREIGN KEY (COLOR_SCHEME_ID) REFERENCES COLOR_SCHEMES(ID)
);

CREATE OR REPLACE TABLE FILES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ORIGINAL_NAME VARCHAR(1000) NOT NULL,
	SERVER_NAME VARCHAR(1000) NOT NULL,
	EXTENSION VARCHAR(100),
	TITLE VARCHAR(1000) NOT NULL,
	DESCRIPTION TEXT,
	UPLOADED_ON DATETIME NOT NULL
);

CREATE OR REPLACE TABLE FILE_PRIVILEGES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT NOT NULL,
	FILE_ID INT NOT NULL,
	PRIVILEGE VARCHAR(10) NOT NULL,

	FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
	FOREIGN KEY (FILE_ID) REFERENCES FILES(ID)
);

CREATE OR REPLACE TABLE FILES_HAVE_CATEGORIES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FILE_ID INT NOT NULL,
	CATEGORY_ID INT NOT NULL,

	FOREIGN KEY (FILE_ID) REFERENCES FILES(ID),
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);
