CREATE OR REPLACE TABLE USERS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	USERNAME VARCHAR(255) NOT NULL UNIQUE,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD_HASH CHAR(60) NOT NULL,
	PROFILE_PICTURE_PATH VARCHAR(255)
);

CREATE OR REPLACE TABLE COLOR_SCHEMES (
	ID INT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	TEXT_COLOR VARCHAR(7) NOT NULL,
	BACKGROUND_COLOR VARCHAR(7) NOT NULL
);

CREATE OR REPLACE TABLE CATEGORIES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	OWNER_ID INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	COLOR_SCHEME_ID INT NOT NULL,

	FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID),
	FOREIGN KEY (COLOR_SCHEME_ID) REFERENCES COLOR_SCHEMES(ID)
);
